### ISSUE TITLE
You happen to use my stuff

### ISSUE THREAD

**Issue by LabRicecat** [PieOfficial/Pie#4]
Heya,
so I see that `src/script` is stuff written by me.
First of all, cool that you are using my things! Thank you!
Second thing, I don't seem to be credited, oh no! 〣( ºΔº )〣
I would appreciate if you add the licenses provided by the repository (all of them are MIT) and maybe add a notice in the readme.md.

It seems like you want to use `carescript`, and all the other stuff happened to be required. I am currently planing to extract carescript from the catcaretaker to get rid of all the dependencies. Maybe consider to not get your things out of date, to use my package manager, the `CatCaretaker`. (￣▽￣)
Setup is simple, as you can see in the tutorial.

Thanks again for using my stuff, but credit would be nice. Thanks! (⌒▽⌒)☆

**Comment by AnimalStudioOfficial** [comment]
I added credit to the `readme.md` file. Would you like me to add licenses to the files I used?

**Comment by LabRicecat** [comment]
Yeah I'd be cool if you add the `LICENSE` of the `CatCaretaker` project into the `script/` directory.
Thanks! (* ^ ω ^)

**Comment by AnimalStudioOfficial** [comment]
Would you like the LICENCE file in the `src/script` directory? (I'm just trying to understand what you want)

**Comment by LabRicecat** [comment]
That would be nice, yes

**Comment by AnimalStudioOfficial** [comment]
Ok I put the `LICENSE`file for `CatCaretaker` in `src/script`.

**Comment by LabRicecat** [comment]
Thanks (* ^ ω ^)

**Comment by AnimalStudioOfficial** [comment]
Your Welcome

**Comment by AnimalStudioOfficial** [comment]
Can I close this issue?

**Comment by LabRicecat** [comment]
Sure!

**Comment by AnimalStudioOfficial** [comment]
Ok
